CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  email  VARCHAR(150) NOT NULL
);

CREATE TABLE producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  precio DECIMAL(12,2) NOT NULL,
  stock  INT NOT NULL
);

CREATE TABLE factura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMP,
  cliente_id BIGINT NOT NULL,
  CONSTRAINT fk_factura_cliente
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE detalle_factura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factura_id  BIGINT NOT NULL,
  producto_id BIGINT NOT NULL,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(12,2) NOT NULL,
  subtotal        DECIMAL(12,2) NOT NULL,
  CONSTRAINT fk_detalle_factura
    FOREIGN KEY (factura_id) REFERENCES factura(id)
      ON DELETE CASCADE,
  CONSTRAINT fk_detalle_producto
    FOREIGN KEY (producto_id) REFERENCES producto(id)
);

CREATE INDEX idx_factura_cliente ON factura(cliente_id);
CREATE INDEX idx_detalle_factura ON detalle_factura(factura_id);
CREATE INDEX idx_detalle_producto ON detalle_factura(producto_id);
